### ISSUE TITLE
The database is not re-created if it does not exist.

### ISSUE THREAD

**Issue by JoyfulReaper** [chrisK00/CRUDRecipeEF#32]
If the database does not exist when the program is launched it should be re-created and seeded.

**Comment by chrisK00** [comment]
The database follows along and is a part of the project. If it doesnt exist in bin it getd there on build with seeded data.

**Comment by JoyfulReaper** [comment]
I was thinking dapper when I created this..

**Comment by JoyfulReaper** [comment]
Still this might be something worth looking into: https://www.entityframeworktutorial.net/code-first/database-initialization-strategy-in-code-first.aspx

**Comment by chrisK00** [comment]
> Still this might be something worth looking into: https://www.entityframeworktutorial.net/code-first/database-initialization-strategy-in-code-first.aspx

Not sure what we can use it for considering the db will always exist (it can be empty tho therefore the seeding)
