### ISSUE TITLE
Update the console menu system to allow assigning and editing the category of recipes

### ISSUE THREAD

**Issue by JoyfulReaper** [chrisK00/CRUDRecipeEF#47]
Update the console menu system to allow assigning and editing the category of recipes

**Comment by sero-dev** [comment]
Mind if I take this one?

**Comment by JoyfulReaper** [comment]
> Mind if I take this one?

@sero-dev Fine with me, but #25 probably should be completed first and not sure if the other prerequisites have been merged. I will try to finish @25 with in an hour or two
